from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = patterns('apps',
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/$', login_required(views.IndexView.as_view()), name='index'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/create/$',
                           login_required(views.SprintCreate.as_view()), name='create'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/update/(?P<pk_sprint>\d+)/$',
                           login_required(views.SprintUpdate.as_view()), name='update'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/backlog/(?P<pk_sprint>\d+)/$',
                           login_required(views.SprintBacklogIndexView.as_view()), name='backlog'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/gestionar/(?P<pk_sprint>\d+)/$',
                           login_required(views.SprintGestionar.as_view()), name='gestionar'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/gestionar/(?P<pk_sprint>\d+)/horas/$',
                           'sprints.views.detalle_horas', name='detalle_horas'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/gestionar/(?P<pk_sprint>\d+)/user_story/(?P<pk_user_story>\d+)/$',
                           login_required(views.SprintGestionarUpdate.as_view()), name='gestionar_update'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/gestionar/(?P<pk_sprint>\d+)/user_story/(?P<pk_user_story>\d+)/delete/$',
                           'sprints.views.desasignar_user_story', name='gestionar_delete'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/iniciar/(?P<pk_sprint>\d+)/$',
                           'sprints.views.iniciar_sprint', name='iniciar'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/kanban/(?P<pk_sprint>\d+)/$',
                           'sprints.views.sprint_kanban', name='kanban'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/kanban/(?P<pk_sprint>\d+)/registrar/(?P<pk_user_story>\d+)/$',
                           login_required(views.RegistrarTarea.as_view()), name='registrar_tarea'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/kanban/(?P<pk_sprint>\d+)/tareas/(?P<pk_user_story>\d+)/$',
                           login_required(views.TareasIndexView.as_view()), name='ver_tareas'),
                       url(r'^tareas/tipos/$',
                           login_required(views.TareasIndexViewAjax.as_view()), name='ver_tareas_ajax'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/kanban/(?P<pk_sprint>\d+)/estado/(?P<pk_user_story>\d+)/$',
                           'sprints.views.cambiar_estado', name='cambiar_estado'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/kanban/(?P<pk_sprint>\d+)/revertir/(?P<pk_user_story>\d+)/$',
                           'sprints.views.revertir_estado', name='revertir_estado'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/kanban/(?P<pk_sprint>\d+)/aprobar/(?P<pk_user_story>\d+)/$',
                           'sprints.views.aprobar_user_story', name='aprobar'),
                       url(r'^proyecto/(?P<pk_proyecto>\d+)/kanban/(?P<pk_sprint>\d+)/adjuntar/(?P<pk_user_story>\d+)/$',
                           'sprints.views.adjuntar_archivo', name='adjuntar_archivo'),
                       #url(r'^proyecto/(?P<pk_proyecto>\d+)/update_sm/(?P<pk_user_story_sm>\d+)/$', login_required(views.UserStoryUpdateSM.as_view()), name='update_sm'),
                       #url(r'^proyecto/(?P<pk_proyecto>\d+)/delete/(?P<pk_user_story>\d+)/$', 'user_stories.views.descartar_user_story', name='delete'),
                       #url(r'^proyecto/(?P<pk_proyecto>\d+)/historial/(?P<pk_user_story>\d+)/$', login_required(views.VerHistorialUserStory.as_view()), name='historial'),
                       #url(r'^(?P<pk>\d+)/$', 'proyectos.views.proyecto_index', name='proyecto_index'),
                       #url(r'^(?P<pk_proyecto>\d+)/equipo/add/$', login_required(views.AddMiembro.as_view()),
                       #    name='add_miembro'),
                       #url(r'^(?P<pk_proyecto>\d+)/equipo/$', 'proyectos.views.listar_equipo', name='equipo_list'),
                       #url(r'^(?P<pk_proyecto>\d+)/equipo/delete/(?P<pk_user>\d+)/$', 'proyectos.views.delete_miembro',
                       #    name='delete_miembro'),
                       #url(r'^(?P<pk_proyecto>\d+)/equipo/rol/(?P<pk_user>\d+)/$',
                       #    login_required(views.RolMiembro.as_view()), name='rol_miembro'),
                       )